### ISSUE TITLE
middleware async issue

### ISSUE THREAD

**Issue by deeprave** [deeprave/yourwishesfuneraladvocacy#5]
There seems to be an async related issue in middleware.
```
app_1    |   File "/usr/lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
app_1    |     response = self.process_response(request, response)
app_1    |   File "/usr/lib/python3.8/site-packages/django/middleware/clickjacking.py", line 26, in process_response
app_1    |     if response.get('X-Frame-Options') is not None:
app_1    | AttributeError: 'coroutine' object has no attribute 'get'
app_1    | ERROR:    Exception in ASGI application
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
app_1    |     result = await app(self.scope, self.receive, self.send)
app_1    |   File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
app_1    |     return await self.app(scope, receive, send)
app_1    |   File "/usr/lib/python3.8/site-packages/django/core/handlers/asgi.py", line 161, in __call__
app_1    |     response = await self.get_response_async(request)
app_1    |   File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 148, in get_response_async
app_1    |     response = await self._middleware_chain(request)
app_1    | TypeError: object HttpResponse can't be used in 'await' expression
app_1    | Internal Server Error: /favicon.ico
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
app_1    |     response = get_response(request)
app_1    |   File "/usr/lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
app_1    |     response = self.process_response(request, response)
app_1    |   File "/usr/lib/python3.8/site-packages/django/middleware/clickjacking.py", line 26, in process_response
app_1    |     if response.get('X-Frame-Options') is not None:
app_1    | AttributeError: 'coroutine' object has no attribute 'get'
app_1    | ERROR:    Exception in ASGI application
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
app_1    |     result = await app(self.scope, self.receive, self.send)
app_1    |   File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
app_1    |     return await self.app(scope, receive, send)
app_1    |   File "/usr/lib/python3.8/site-packages/django/core/handlers/asgi.py", line 161, in __call__
app_1    |     response = await self.get_response_async(request)
app_1    |   File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 148, in get_response_async
app_1    |     response = await self._middleware_chain(request)
app_1    | TypeError: object HttpResponse can't be used in 'await' expression
app_1    | INFO:     172.24.0.1:45182 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
w^CERROR: Aborting.```

Cause of the issue seems to be when HttpBadRequest is raised when a middleware is not yet async aware.

**Comment by deeprave** [comment]
Since nothing (yet) uses Django async capability, switching to gunicorn and WSGI interface should solve the issue
